### ISSUE TITLE
2 Small Typos

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/introduction-to-data-science#1]
* 3rd sentence has an extra "the" ...."We know that THE just the word math provokes fear..."
* Sentence "It's time to give it A honest try."  should be "an" honest try. 
Love ya' Flatiron...enjoyed the text, just trying to keep us the best!

"2. Accessible

This course was designed to be accessible to everyone.

Math is a four letter word: Listen up, we do not expect you to walk in here a math person. We know that the just the word math provokes fear and boredom -- somehow simultaneously! Still, we won't shy away from it. Chances are you learned math through pencil and paper, not through programming graphs and equations that automatically respond to your inputs. It's time to give it a honest try."

**Comment by LoreDirick** [comment]
Small typos fixed
Thanks for raising @ccklight !
